apiVersion: 1

datasources:
  - name: PostgresDWH
    type: postgres
    uid: my_postgres_uid      # Уникальный ID
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "disable"
      postgresVersion: 1200
    isDefault: true